### ISSUE TITLE
Error with inclusivelint

### ISSUE THREAD

**Issue by bubbletroubles** [squassina/doc-pipeline#1]
The pipeline has a task for `inclusivelint` but doesnt install it.

E.g. in linter.yml

```yaml
  - task: Npm@1
    displayName: "Run Inclusive Lint"
    continueOnError: true
    inputs:
      command: custom
      customCommand: "run inclusivelint"
```
But this step fails in the pipeline

```
/usr/local/bin/npm run inclusivelint
npm ERR! Missing script: "inclusivelint"
npm ERR! 
npm ERR! To see a list of scripts, run:
npm ERR!   npm run
```
